"""Build a fixed RGB332 footer atlas from the checked-in upstream SVGs.

Requires Pillow and scripts/rasterize-icons.mjs. Render source SVGs at 384px,
alpha-crop/aspect-fit with Lanczos, then Floyd-Steinberg quantize to RGB332.
No source fetching occurs in this reproducible build or on the device.
"""
import hashlib
import json
from pathlib import Path
from PIL import Image, ImageOps

root=Path(__file__).resolve().parent.parent
sources=root/'assets/footer'
manifest=json.loads((sources/'sources.json').read_text())
lines=['// Generated by scripts/build-footer-icons.py; upstream notices in assets/footer.',
       '#pragma once', '#include <stdint.h>', '#include <pgmspace.h>',
       'struct FooterIcon {uint8_t width,height; const uint8_t* pixels; const uint16_t* mask;};']
palette=Image.new('P',(1,1))
colors=[]
for value in range(256):
    r=value&0xe0;r|=r>>3;r|=r>>6
    g=(value&0x1c)<<3;g|=g>>3;g|=g>>6
    colors.extend((r,g,(value&3)*85))
palette.putpalette(colors)
for name,item in manifest.items():
    path=sources/item['file']
    assert hashlib.sha256(path.read_bytes()).hexdigest()==item['sha256'],name
    source=Image.open(str(path)+'.png').convert('RGBA')
    width,height=(11,20) if name.startswith('Gesture') else (16,16)
    # Gesture markers retain the same SVG viewbox/scale/baseline, so a dot,
    # two dots and a dash align without enlarging the single dot into a ball.
    source=ImageOps.contain(source if name.startswith('Gesture') else source.crop(source.getchannel('A').getbbox()),(width,height if name.startswith('Gesture') else height-2),Image.Resampling.LANCZOS)
    icon=Image.new('RGBA',(width,height));icon.paste(source,((width-source.width)//2,(height-source.height)//2))
    backdrop=Image.new('RGB',icon.size,(24,28,56));backdrop.paste(icon,mask=icon.getchannel('A'))
    quantized=backdrop.quantize(palette=palette,dither=Image.Dither.FLOYDSTEINBERG)
    mask=[sum(0x8000>>x for x in range(width) if icon.getpixel((x,y))[3]>=40) for y in range(height)]
    values=','.join(str(v) for v in quantized.tobytes())
    lines += [f'// {item["url"]}; source SHA-256 {item["sha256"]}',
              f'static const uint8_t footer{name}Pixels[] PROGMEM={{{values}}};',
              f'static const uint16_t footer{name}Mask[] PROGMEM={{{",".join(str(v) for v in mask)}}};',
              f'static const FooterIcon footer{name}={{{width},{height},footer{name}Pixels,footer{name}Mask}};']
(root/'firmware/footer_icons.h').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({'icons':len(manifest),'palette':'RGB332','dither':'Floyd-Steinberg'}))
